version: 2

workflows:
  version: 2
  workflow:
    jobs:

      - test:
          filters:
            tags:
              only: /.*/

      - deploy:
          requires: [ 'test' ]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

jobs:

  test:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout

      - run:
         name: npm install
         command: npm install

      - run:
         name: npm run ci
         command: npm run ci

  deploy:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout

      - run:
         name: npm login
         command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
         name: npm publish
         command: npm publish