version: 2

workflows:
  version: 2
  plan_and_apply:
    jobs:

      - test

jobs:

  test:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout

      - run: 
         name: npm install
         command: npm install

      - run: 
         name: npm run ci
         command: npm run ci
